### ISSUE TITLE
comments issue of version 0.2

### ISSUE THREAD

**Issue by haifenghan** [Asalle/flatbuffers-mode#1]
Testing it on the file with version 0.2 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs#L28

Comment part is not colored while "IMPORTANT: All" is in color.

Please see the following screen shot:

![image](https://user-images.githubusercontent.com/4157827/69319618-7794b800-0c7a-11ea-9494-3febf06f9a22.png)

**Comment by haifenghan** [comment]
By the way, the keywords: namespace, file_identifier and file_extension are not regognized.

**Comment by Asalle** [comment]
Hey, thanks for the issue! I'll take a look this weekend.

**Comment by Asalle** [comment]
Hey, I looked into it and I'll make sure to add all of the keywords later this week. But comments seem to be more complex issue, I'll have to take some time to tackle that.

**Comment by haifenghan** [comment]
OK
Thanks for your time.

Best regards

**Comment by Asalle** [comment]
@haifenghan check out the `asalle/make-comments-matching-precise` branch, it almost matches all the comments in the document you provided! :) 
I'm still not sure what's the deal with a couple of bugs, but generally it's okay! :D

**Comment by haifenghan** [comment]
@Asalle It works.
Thanks

**Comment by haifenghan** [comment]
Next, we could support more key works, such as namespace, file_identifier, file_extension, numbers, strings, etc.

![image](https://user-images.githubusercontent.com/4157827/77218929-b0cb2f00-6b6b-11ea-9238-fe82819d8eb5.png)

**Comment by Asalle** [comment]
@haifenghan thanks for the feedback! I added support for file_* keywords in master, numbers and strings should be picked up automatically by c-mode
I'll close this issue, but feel free to open a new one should any issues arise! :smiley_cat:
