### ISSUE TITLE
Please upload this to melpa

### ISSUE THREAD

**Issue by yesudeep** [Asalle/flatbuffers-mode#3]
Could you please upload this package to melpa?

**Comment by Asalle** [comment]
@yesudeep thanks for the suggestion, I'll start working on it today, let's see how it goes! :+1:

**Comment by Asalle** [comment]
I submitted a pr, let's see what they say
https://github.com/melpa/melpa/pull/7029

**Comment by Asalle** [comment]
it's there! :tada: :D 
I'll close the issue if that's okay

**Comment by yesudeep** [comment]
Yay! Thank you!
